import assert from "node:assert/strict";
import test from "node:test";
import { readFile, readdir, stat } from "node:fs/promises";

test("build contains the Finora product experience", async () => {
  const landing = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const install = await readFile(new URL("../app/install/page.tsx", import.meta.url), "utf8");
  const dashboard = await readFile(new URL("../app/dashboard/page.tsx", import.meta.url), "utf8");
  const askRoute = await readFile(new URL("../app/api/ask/route.ts", import.meta.url), "utf8");
  const chatsRoute = await readFile(new URL("../app/api/chats/route.ts", import.meta.url), "utf8");
  const sheetRoute = await readFile(new URL("../app/api/sheets/route.ts", import.meta.url), "utf8");
  const agentRoute = await readFile(new URL("../app/api/agent/route.ts", import.meta.url), "utf8");
  const statementParser = await readFile(new URL("../lib/statement-parser.ts", import.meta.url), "utf8");
  const actions = await readFile(new URL("../lib/agent-actions.ts", import.meta.url), "utf8");
  const analyst = await readFile(new URL("../lib/analyst.ts", import.meta.url), "utf8");
  const page = `${landing}\n${dashboard}`;
  const assetsDirectory = new URL("../dist/client/assets/", import.meta.url);
  const assets = await readdir(assetsDirectory);
  assert.ok(assets.some((asset) => asset.startsWith("page-") && asset.endsWith(".js")), "missing compiled page asset");
  assert.match(page, /Finora|finora/); assert.match(page, /Your money/); assert.match(page, /Transactions/); assert.match(page, /FINANCIAL HEALTH/); assert.match(page, /SUBSCRIPTIONS/); assert.match(page, /Google Sheets|Sync Sheets/);
  assert.match(page, /Sign in/); assert.match(page, /AI Reports/); assert.match(page, /Every Sunday/); assert.match(page, /First of every month/);
  assert.match(dashboard, /Create Finora Financial Dashboard/); assert.match(dashboard, /Open Sheet/); assert.match(dashboard, /Disconnect from Finora/);
  assert.doesNotMatch(dashboard, /Apps Script web app URL|Matches FINORA_SECRET/);
  assert.match(landing, /Every statement/); assert.match(landing, /The MCP is/); assert.match(landing, /Raw files are never kept/);
  assert.match(landing, /finora-finance\.zip/); assert.match(landing, /window\.location\.href = "\/install"/);
  assert.match(install, /Three small steps/); assert.match(install, /INSTALL FROM GITHUB/); assert.match(install, /\$finora-finance skill-sync/); assert.match(install, /\/finance skill-sync/);
  assert.ok((await stat(new URL("../public/downloads/finora-finance.zip", import.meta.url))).size > 1_000, "missing packaged Finora skill");
  assert.match(dashboard, /No sample transactions\. Your dashboard starts empty\./);
  assert.match(dashboard, /AnalystReport/); assert.match(dashboard, /What Finora noticed/); assert.match(dashboard, /VISUAL BREAKDOWN/);
  assert.match(dashboard, /sidebar-agent-section/); assert.match(dashboard, /sidebar-new-chat/); assert.match(dashboard, /RECENT CHATS/);
  assert.doesNotMatch(dashboard, /finora-chat-header|finora-chat-history|finora-history-new/);
  assert.match(askRoute, /buildAnalystResponse/); assert.match(askRoute, /proactive, evidence-based personal finance analyst/);
  assert.match(dashboard, /Attach financial files/); assert.match(dashboard, /multiple hidden/); assert.match(dashboard, /READY TO DO/); assert.match(dashboard, /runAgentAction/);
  assert.match(dashboard, /chatAttachmentsRef/); assert.match(dashboard, /evidenceScope/); assert.match(askRoute, /ATTACHED FILES ONLY/); assert.match(analyst, /rollingMonths/);
  assert.match(dashboard, /attachmentContext/); assert.match(dashboard, /asksForSavedData/); assert.match(dashboard, /statementFromAttachments/); assert.match(chatsRoute, /cleanAttachmentContext/);
  assert.match(sheetRoute, /statementOverride/); assert.match(askRoute, /every follow-up pronoun/); assert.match(actions, /Write the .*attached file/);
  assert.match(actions, /open_sheet/); assert.match(actions, /import_attachments/); assert.match(actions, /recategorize_transactions/); assert.match(actions, /append_sheet_rows/); assert.match(actions, /update_sheet_range/); assert.match(actions, /schedule_report/);
  assert.match(sheetRoute, /addTab/); assert.match(sheetRoute, /deleteTab/); assert.match(sheetRoute, /appendRows/); assert.match(sheetRoute, /updateRange/); assert.match(sheetRoute, /clearRange/);
  assert.match(agentRoute, /processStatementInput/); assert.match(agentRoute, /answerWithFinora/); assert.match(statementParser, /parseCsvFallback/); assert.doesNotMatch(agentRoute, /fetch\(new URL\("\/api\/(?:categorize|ask)"/);
  assert.doesNotMatch(dashboard, /Finding transactions with/);
  assert.doesNotMatch(page, /sampleStatement|defaultBudgets|codex-preview|Your site is taking shape|react-loading-skeleton/);
});
