#!/usr/bin/env node
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import fs from "node:fs/promises";
import path from "node:path";
import { configuredProviders, generateWithFallback } from "../lib/ai-providers.mjs";
import {
  analyzeFinances,
  buildFinanceGraph,
  buildFinancialTimeline,
  explainBudgetExceeded,
  explainSpendingChange,
  financialHealthReport,
  findCostCutting,
  findSavingsOpportunities,
  predictMonthEndSpending,
  suggestBudgets,
} from "../lib/finance-intelligence.mjs";

const DATA_DIR = path.resolve(process.env.FINORA_DATA_DIR || ".finora");
const LEDGER_PATH = path.join(DATA_DIR, "ledger.json");
const categories = ["Food & Dining", "Housing", "Transport", "Shopping", "Bills & Utilities", "EMI", "Investment", "Health", "Entertainment", "Travel", "Salary", "Income", "Transfers", "Miscellaneous", "Other"];
const transactionInput = z.object({ id: z.string().optional(), date: z.string(), merchant: z.string().optional(), description: z.string(), amount: z.number(), type: z.enum(["debit", "credit"]), category: z.string().optional(), confidence: z.number().optional(), source: z.string().optional(), explanation: z.string().optional() }).passthrough();
const budgetInput = z.object({ category: z.string(), limit: z.number().positive() });

function normalizeMerchant(raw = "") {
  const value = raw.toUpperCase().replace(/\b(UPI|P2M|P2P|POS|ACH|SI|BBPS|NEFT|IMPS|TXN|REF)\b/g, " ").replace(/\b\d{6,}\b/g, " ").replace(/[\/_*\-]+/g, " ").replace(/\s+/g, " ").trim();
  const known = [[/AMZN|AMAZON/, "Amazon"], [/SWIGGY/, "Swiggy"], [/ZOMATO/, "Zomato"], [/BLINKIT|GROFERS/, "Blinkit"], [/UBER/, "Uber"], [/NETFLIX/, "Netflix"], [/SPOTIFY/, "Spotify"], [/OPENAI|CHATGPT/, "ChatGPT"], [/ANTHROPIC|CLAUDE/, "Claude"], [/GOOGLE ONE/, "Google One"], [/CULT|CUREFIT/, "Cult.fit"], [/PRIME/, "Amazon Prime"], [/CANVA/, "Canva"], [/MYNTRA/, "Myntra"], [/INDIGO/, "IndiGo"], [/RELIANCE JIO|\bJIO\b/, "Jio"], [/BESCOM/, "BESCOM"], [/BLUE TOKAI/, "Blue Tokai"]];
  const match = known.find(([pattern]) => pattern.test(value));
  return match?.[1] || value.split(" ").filter(Boolean).slice(0, 4).map((part) => part[0] + part.slice(1).toLowerCase()).join(" ") || "Unknown merchant";
}

function categoryFor(description, credit = false) {
  if (credit) return /salary|payroll/i.test(description) ? "Salary" : "Income";
  const s = description.toLowerCase();
  if (/emi|loan repayment|bajaj finance|home loan|car loan/.test(s)) return "EMI";
  if (/sip|mutual fund|index fund|zerodha|groww|investment/.test(s)) return "Investment";
  if (/swiggy|zomato|blinkit|zepto|restaurant|cafe|coffee|food|grocery/.test(s)) return "Food & Dining";
  if (/rent|housing|maintenance/.test(s)) return "Housing";
  if (/uber|ola|rapido|metro|fuel|petrol|irctc/.test(s)) return "Transport";
  if (/amazon|flipkart|myntra|ajio|retail/.test(s)) return "Shopping";
  if (/electric|bescom|airtel|jio|broadband|water|gas|bbps/.test(s)) return "Bills & Utilities";
  if (/hospital|pharmacy|medical|cult|gym|health/.test(s)) return "Health";
  if (/netflix|spotify|cinema|bookmyshow|hotstar|prime|canva|chatgpt|claude/.test(s)) return "Entertainment";
  if (/airline|indigo|hotel|makemytrip|booking/.test(s)) return "Travel";
  if (/transfer|imps|p2p/.test(s)) return "Transfers";
  return "Miscellaneous";
}

const periodKey = (date) => { const parsed = new Date(date); return Number.isNaN(parsed.getTime()) ? String(date).slice(0, 7) : `${parsed.getFullYear()}-${String(parsed.getMonth() + 1).padStart(2, "0")}`; };
const latestPeriod = (transactions) => [...new Set(transactions.map((t) => periodKey(t.date)))].sort().at(-1) || "";
const inPeriod = (transactions, period = latestPeriod(transactions)) => transactions.filter((t) => periodKey(t.date) === period);
const currency = (value) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value);

function summarize(transactions) {
  const income = transactions.filter((t) => t.type === "credit").reduce((a, t) => a + t.amount, 0);
  const spend = transactions.filter((t) => t.type === "debit" && !["Transfers", "Investment"].includes(t.category)).reduce((a, t) => a + t.amount, 0);
  const transfers = transactions.filter((t) => t.type === "debit" && ["Transfers", "Investment"].includes(t.category)).reduce((a, t) => a + t.amount, 0);
  const byCategory = transactions.filter((t) => t.type === "debit" && !["Transfers", "Investment"].includes(t.category)).reduce((a, t) => ({ ...a, [t.category]: (a[t.category] || 0) + t.amount }), {});
  return { income, spend, transfers, saved: income - spend - transfers, savingsRate: income ? (income - spend - transfers) / income : 0, transactionCount: transactions.length, byCategory };
}

function monthlySummaries(transactions) { return [...new Set(transactions.map((t) => periodKey(t.date)))].sort().map((period) => ({ period, ...summarize(inPeriod(transactions, period)) })); }
function compareMonths(transactions, current = latestPeriod(transactions), previous) { const periods = [...new Set(transactions.map((t) => periodKey(t.date)))].sort(); const prior = previous || periods[periods.indexOf(current) - 1] || ""; const now = summarize(inPeriod(transactions, current)), before = summarize(inPeriod(transactions, prior)); return { current, previous: prior, currentSummary: now, previousSummary: before, spendChangePercent: before.spend ? ((now.spend - before.spend) / before.spend) * 100 : null }; }

function subscriptions(transactions) {
  const groups = transactions.filter((t) => t.type === "debit").reduce((acc, transaction) => { const merchant = normalizeMerchant(transaction.merchant || transaction.description); (acc[merchant] ||= []).push(transaction); return acc; }, {});
  return Object.entries(groups).flatMap(([merchant, items]) => { const sorted = items.sort((a, b) => new Date(a.date) - new Date(b.date)); const average = sorted.reduce((a, t) => a + t.amount, 0) / sorted.length; const stable = sorted.every((t) => Math.abs(t.amount - average) / Math.max(average, 1) <= .12); const intervals = sorted.slice(1).map((item, index) => (new Date(item.date) - new Date(sorted[index].date)) / 86400000); const cadence = intervals.some((days) => days >= 24 && days <= 38); const known = /Netflix|Spotify|ChatGPT|Claude|Cult\.fit|Prime|Google One|Apple|Canva/i.test(merchant); if (!(sorted.length >= 2 && stable && cadence) && !(known && sorted.length >= 1)) return []; const renewal = new Date(sorted.at(-1).date); renewal.setDate(renewal.getDate() + 30); return [{ merchant, monthlyCost: Math.round(average), annualCost: Math.round(average * 12), occurrences: sorted.length, estimatedRenewalDate: renewal.toISOString().slice(0, 10), confidence: cadence ? .94 : .72, transactionIds: sorted.map((t) => t.id) }]; }).sort((a, b) => b.monthlyCost - a.monthlyCost);
}

function duplicates(transactions) { const sorted = transactions.filter((t) => t.type === "debit").sort((a, b) => new Date(a.date) - new Date(b.date)); const result = []; for (let i = 0; i < sorted.length; i++) for (let j = i + 1; j < Math.min(sorted.length, i + 5); j++) { const first = sorted[i], second = sorted[j], minutes = Math.abs(new Date(second.date) - new Date(first.date)) / 60000; if (normalizeMerchant(first.merchant) === normalizeMerchant(second.merchant) && Math.abs(first.amount - second.amount) <= 1 && minutes <= 2) result.push({ merchant: normalizeMerchant(first.merchant), amount: first.amount, minutesApart: Math.round(minutes), transactionIds: [first.id, second.id] }); } return result; }

function anomalies(transactions) { const latest = latestPeriod(transactions), historical = new Set(transactions.filter((t) => periodKey(t.date) !== latest).map((t) => normalizeMerchant(t.merchant))); const result = inPeriod(transactions, latest).filter((t) => t.type === "debit" && t.amount >= 4999 && !historical.has(normalizeMerchant(t.merchant))).map((t) => ({ severity: t.amount >= 10000 ? "high" : "medium", title: `New merchant charged ${currency(t.amount)}`, detail: `${normalizeMerchant(t.merchant)} has not appeared before.`, transactionId: t.id })); const comparison = compareMonths(transactions); Object.keys(comparison.currentSummary.byCategory).forEach((category) => { const now = comparison.currentSummary.byCategory[category] || 0, before = comparison.previousSummary.byCategory[category] || 0; if (before && now - before > 1000 && now / before >= 1.5) result.push({ severity: now / before >= 2 ? "high" : "medium", title: `${category} jumped ${Math.round((now / before - 1) * 100)}%`, detail: `${currency(now)} versus ${currency(before)} previously.` }); }); return result; }

function budgetStatus(transactions, budgets, period = latestPeriod(transactions)) { const byCategory = summarize(inPeriod(transactions, period)).byCategory; return budgets.map((budget) => { const spent = byCategory[budget.category] || 0; return { ...budget, spent, remaining: budget.limit - spent, usedPercent: budget.limit ? spent / budget.limit * 100 : 0, status: spent > budget.limit ? "over" : spent / budget.limit >= .8 ? "warning" : "on-track" }; }); }
function healthScore(transactions, budgets = []) { const totals = summarize(inPeriod(transactions)); const status = budgetStatus(transactions, budgets); const recurringRatio = totals.income ? subscriptions(transactions).reduce((a, s) => a + s.monthlyCost, 0) / totals.income : 0; const parts = { savings: Math.max(0, Math.min(35, totals.savingsRate * 70)), budget: status.length ? Math.max(0, 25 - status.filter((b) => b.status === "over").length * 8 - status.filter((b) => b.status === "warning").length * 3) : 15, recurring: Math.max(0, 20 - recurringRatio * 100), consistency: Math.max(0, 20 - anomalies(transactions).length * 4) }; const score = Math.round(Object.values(parts).reduce((a, n) => a + n, 0)); return { score, label: score >= 80 ? "Excellent" : score >= 65 ? "Healthy" : score >= 45 ? "Needs attention" : "At risk", breakdown: Object.fromEntries(Object.entries(parts).map(([k, v]) => [k, Math.round(v)])) }; }

function splitCsv(line, delimiter) { const cells = []; let value = "", quoted = false; for (let i = 0; i < line.length; i++) { const char = line[i]; if (char === '"' && line[i + 1] === '"') { value += '"'; i++; } else if (char === '"') quoted = !quoted; else if (char === delimiter && !quoted) { cells.push(value.trim()); value = ""; } else value += char; } cells.push(value.trim()); return cells; }
function parseCsv(text, source) { const lines = text.split(/\r?\n/).filter(Boolean), delimiter = lines[0]?.includes("\t") ? "\t" : lines[0]?.includes(";") ? ";" : ",", headers = splitCsv(lines[0] || "", delimiter).map((h) => h.toLowerCase()), find = (...names) => headers.findIndex((h) => names.some((n) => h.includes(n))); const date = find("date"), description = find("description", "narration", "details", "merchant", "particular", "remark"), debit = find("debit", "withdrawal"), credit = find("credit", "deposit"), amount = find("amount"), type = find("type", "dr/cr"); if (description < 0 || (debit < 0 && credit < 0 && amount < 0)) throw new Error("Could not identify statement columns."); const number = (value = "") => Number(value.replace(/[^0-9.-]/g, "")) || 0; return lines.slice(1).map((line, index) => { const row = splitCsv(line, delimiter), creditAmount = credit >= 0 ? number(row[credit]) : 0, debitAmount = debit >= 0 ? number(row[debit]) : 0, isCredit = creditAmount > 0 || /cr|credit|deposit/i.test(row[type] || ""), raw = row[description] || "Unknown transaction"; return { id: `txn-${Date.now()}-${index + 1}`, date: row[date] || new Date().toISOString().slice(0, 10), merchant: raw, description: raw, amount: Math.abs(amount >= 0 ? number(row[amount]) : creditAmount || debitAmount), type: isCredit ? "credit" : "debit", category: "Other", confidence: .5, source, explanation: "Parsed from source; not categorized yet." }; }).filter((t) => t.amount > 0); }

const rawStatementSchema = { type: "object", additionalProperties: false, properties: { transactions: { type: "array", items: { type: "object", additionalProperties: false, properties: { date: { type: "string" }, merchant: { type: "string" }, description: { type: "string" }, amount: { type: "number" }, type: { type: "string", enum: ["debit", "credit"] } }, required: ["date", "merchant", "description", "amount", "type"] } } }, required: ["transactions"] };
const categorizedStatementSchema = { type: "object", additionalProperties: false, properties: { transactions: { type: "array", items: { type: "object", additionalProperties: false, properties: { id: { type: "string" }, date: { type: "string" }, merchant: { type: "string" }, description: { type: "string" }, amount: { type: "number" }, type: { type: "string", enum: ["debit", "credit"] }, category: { type: "string", enum: categories }, confidence: { type: "number" }, source: { type: "string" }, explanation: { type: "string" } }, required: ["id", "date", "merchant", "description", "amount", "type", "category", "confidence", "source", "explanation"] } } }, required: ["transactions"] };

async function extractDocument(filePath) {
  if (!configuredProviders().vertex) throw new Error("PDF and image statements require GOOGLE_VERTEX_CREDENTIALS; CSV works offline.");
  const buffer = await fs.readFile(filePath), extension = path.extname(filePath).toLowerCase(), mime = extension === ".pdf" ? "application/pdf" : extension === ".png" ? "image/png" : "image/jpeg";
  const result = await generateWithFallback({ system: "Extract every transaction from this financial document without categorizing it. Never invent rows. Amount must be positive; type is debit or credit.", prompt: `Source filename: ${path.basename(filePath)}. Return every transaction.`, schema: rawStatementSchema, media: { mimeType: mime, data: buffer.toString("base64") } });
  const parsed = JSON.parse(result.text.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, ""));
  return (parsed.transactions || []).map((t, i) => ({ ...t, id: `txn-${Date.now()}-${i + 1}`, category: "Other", confidence: .5, source: path.basename(filePath), explanation: `Parsed by ${result.model}; not categorized yet.` }));
}
async function parseFile(filePath) { const resolved = path.resolve(filePath), extension = path.extname(resolved).toLowerCase(); return [".csv", ".tsv", ".txt"].includes(extension) ? parseCsv(await fs.readFile(resolved, "utf8"), path.basename(resolved)) : extractDocument(resolved); }
async function categorize(transactions) {
  const local = () => transactions.map((t) => ({ ...t, id: t.id || `txn-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`, merchant: normalizeMerchant(t.merchant || t.description), category: categoryFor(t.description, t.type === "credit"), confidence: .74, source: t.source || "import", explanation: "Categorized locally from merchant and narration signals." }));
  if (!configuredProviders().vertex && !configuredProviders().groq) return local();
  try {
    const result = await generateWithFallback({ system: `Normalize merchants and categorize transactions into: ${categories.join(", ")}. Separate P2P Transfers, EMI and Investment from consumption. Preserve every transaction and id; add confidence and a short explanation.`, prompt: JSON.stringify(transactions), schema: categorizedStatementSchema });
    return JSON.parse(result.text.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, "")).transactions || local();
  } catch { return local(); }
}

async function answerLedgerQuestion(question, transactions) {
  try {
    const generated = await generateWithFallback({ system: "You are Finora, a concise evidence-based personal finance analyst. Answer only from the supplied ledger. Treat Investments and Transfers separately from consumption. Mention exact merchants and amounts when relevant. Flag uncertainty. Do not provide investment, tax, or legal advice.", prompt: `Question: ${question}\n\nLedger: ${JSON.stringify(transactions)}` });
    return generated.text;
  } catch {
    const lower = question.toLowerCase(), total = summarize(inPeriod(transactions)), foundSubscriptions = subscriptions(transactions), foundDuplicates = duplicates(transactions), comparison = compareMonths(transactions);
    if (/subscription|recurring/.test(lower)) return `Found ${foundSubscriptions.length} subscriptions costing ${currency(foundSubscriptions.reduce((a, s) => a + s.monthlyCost, 0))}/month.`;
    if (/duplicate|twice/.test(lower)) return foundDuplicates.length ? `Found ${foundDuplicates.length} possible duplicate payments: ${foundDuplicates.map((d) => `${d.merchant} ${currency(d.amount)}`).join(", ")}.` : "No two-minute duplicate payments found.";
    if (/compare|last month/.test(lower)) return comparison.spendChangePercent == null ? "Import two months to compare." : `Spending is ${Math.abs(comparison.spendChangePercent).toFixed(0)}% ${comparison.spendChangePercent >= 0 ? "higher" : "lower"} than ${comparison.previous}.`;
    const top = Object.entries(total.byCategory).sort((a, b) => b[1] - a[1])[0];
    return `${top?.[0] || "Spending"} is largest at ${currency(top?.[1] || 0)}; total spend is ${currency(total.spend)}.`;
  }
}

async function loadLedger() { try { return JSON.parse(await fs.readFile(LEDGER_PATH, "utf8")); } catch { return { currency: "INR", transactions: [], updatedAt: null }; } }
async function saveLedger(ledger) { await fs.mkdir(DATA_DIR, { recursive: true }); ledger.updatedAt = new Date().toISOString(); await fs.writeFile(LEDGER_PATH, JSON.stringify(ledger, null, 2)); }
const result = (text, data) => ({ content: [{ type: "text", text }], structuredContent: data });

const server = new McpServer({ name: "finora", version: "2.0.0" });

// Outcome-focused tools are the primary product surface. The composable and low-level
// tools below remain available when an agent needs review or precision edits.
server.registerTool("sync_statement", { title: "Sync statement", description: "Parse, normalize, categorize, save, analyze, and optionally sync one statement in a coordinated workflow.", inputSchema: { filePath: z.string(), replace: z.boolean().optional().default(false), webhookUrl: z.string().url().optional(), secret: z.string().optional() } }, async ({ filePath, replace, webhookUrl, secret }) => {
  const parsed = await parseFile(filePath), categorized = await categorize(parsed), ledger = replace ? { currency: "INR", transactions: [] } : await loadLedger();
  ledger.transactions = [...ledger.transactions, ...categorized].filter((item, index, all) => all.findIndex((candidate) => candidate.id === item.id || (candidate.date === item.date && candidate.amount === item.amount && candidate.description === item.description)) === index);
  await saveLedger(ledger);
  let sheet = null;
  if (webhookUrl) {
    const response = await fetch(webhookUrl, { method: "POST", headers: { "Content-Type": "text/plain;charset=utf-8" }, body: JSON.stringify({ secret, statement: { ...ledger, period: latestPeriod(ledger.transactions) } }), redirect: "follow" });
    sheet = JSON.parse(await response.text());
    if (!response.ok || sheet.ok === false) throw new Error(sheet.error || "Sheets sync failed.");
  }
  const analysis = analyzeFinances(ledger.transactions, []);
  return result(`Imported ${categorized.length} transactions and built a ${analysis.period || "ledger"} financial analysis${sheet ? " with a Sheets sync" : ""}.`, { imported: categorized.length, totalTransactions: ledger.transactions.length, analysis, sheet });
});
server.registerTool("analyze_finances", { title: "Analyze finances", description: "Return a comprehensive, evidence-backed analysis with cash flow, composition, merchants, trends, anomalies, forecast, timeline, and graph relationships.", inputSchema: { transactions: z.array(transactionInput).optional(), budgets: z.array(budgetInput).optional(), period: z.string().optional() }, annotations: { readOnlyHint: true } }, async ({ transactions, budgets, period }) => { const source = transactions || (await loadLedger()).transactions, analysis = analyzeFinances(source, budgets || [], period); return result(`Analyzed ${analysis.period || "the ledger"}: ${currency(analysis.cashFlow.consumption)} consumption and ${currency(analysis.cashFlow.netCashFlow)} net cash flow.`, { analysis }); });
server.registerTool("generate_dashboard", { title: "Generate financial dashboard", description: "Build structured dashboard data and optionally sync it through the configured Finora Sheets webhook.", inputSchema: { transactions: z.array(transactionInput).optional(), budgets: z.array(budgetInput).optional(), period: z.string().optional(), webhookUrl: z.string().url().optional(), secret: z.string().optional() } }, async ({ transactions, budgets, period, webhookUrl, secret }) => { const source = transactions || (await loadLedger()).transactions, dashboard = analyzeFinances(source, budgets || [], period); let sheet = null; if (webhookUrl) { const response = await fetch(webhookUrl, { method: "POST", headers: { "Content-Type": "text/plain;charset=utf-8" }, body: JSON.stringify({ secret, statement: { transactions: source, currency: "INR", period: dashboard.period, insights: dashboard.timeline.map((item) => item.title) } }), redirect: "follow" }); sheet = JSON.parse(await response.text()); if (!response.ok || sheet.ok === false) throw new Error(sheet.error || "Sheets sync failed."); } return result(`Generated the ${dashboard.period || "ledger"} financial dashboard${sheet ? " and synced it" : ""}.`, { dashboard, sheet }); });
server.registerTool("find_savings", { title: "Find savings opportunities", description: "Identify evidence-backed recurring costs and categories above their recent baseline.", inputSchema: { transactions: z.array(transactionInput).optional(), period: z.string().optional() }, annotations: { readOnlyHint: true } }, async ({ transactions, period }) => { const source = transactions || (await loadLedger()).transactions, opportunities = findSavingsOpportunities(source, period); return result(`Found ${opportunities.length} evidence-backed savings opportunities.`, { opportunities }); });
server.registerTool("financial_health_report", { title: "Financial health report", description: "Explain cash flow, savings, budgets, subscriptions, anomalies, and the transparent health score.", inputSchema: { transactions: z.array(transactionInput).optional(), budgets: z.array(budgetInput).optional(), period: z.string().optional() }, annotations: { readOnlyHint: true } }, async ({ transactions, budgets, period }) => { const report = financialHealthReport(transactions || (await loadLedger()).transactions, budgets || [], period); return result(`Financial health is ${report.label} at ${report.score}/100.`, report); });
server.registerTool("explain_spending_change", { title: "Explain spending change", description: "Identify the category and merchant drivers behind a change between two periods.", inputSchema: { transactions: z.array(transactionInput).optional(), current: z.string().optional(), previous: z.string().optional() }, annotations: { readOnlyHint: true } }, async ({ transactions, current, previous }) => { const explanation = explainSpendingChange(transactions || (await loadLedger()).transactions, current, previous); return result(`Explained the change from ${explanation.previous || "the prior period"} to ${explanation.current || "the latest period"}.`, explanation); });
server.registerTool("why_is_budget_exceeded", { title: "Explain budget overrun", description: "Trace a budget overrun to its largest supporting transactions.", inputSchema: { transactions: z.array(transactionInput).optional(), budgets: z.array(budgetInput), category: z.string().optional(), period: z.string().optional() }, annotations: { readOnlyHint: true } }, async ({ transactions, budgets, category, period }) => { const explanation = explainBudgetExceeded(transactions || (await loadLedger()).transactions, budgets, category, period); return result(explanation.exceeded.length ? `${explanation.exceeded.length} budget${explanation.exceeded.length === 1 ? " is" : "s are"} over the limit.` : "No selected budget is over its limit.", explanation); });
server.registerTool("suggest_budget", { title: "Suggest budgets", description: "Suggest evidence-based category limits from up to three recent months and an explicit buffer.", inputSchema: { transactions: z.array(transactionInput).optional(), bufferPercent: z.number().min(0).max(50).optional().default(10) }, annotations: { readOnlyHint: true } }, async ({ transactions, bufferPercent }) => { const suggestions = suggestBudgets(transactions || (await loadLedger()).transactions, bufferPercent); return result(`Suggested ${suggestions.length} category budgets from recent spending.`, { suggestions }); });
server.registerTool("find_cost_cutting", { title: "Find cost-cutting opportunities", description: "Find realistic, ledger-supported reductions without generic or investment advice.", inputSchema: { transactions: z.array(transactionInput).optional(), period: z.string().optional() }, annotations: { readOnlyHint: true } }, async ({ transactions, period }) => { const findings = findCostCutting(transactions || (await loadLedger()).transactions, period); return result(`Potential reductions total about ${currency(findings.totalMonthlyPotential)} per month if the user chooses them.`, findings); });
server.registerTool("predict_month_end_spending", { title: "Predict month-end spending", description: "Estimate month-end consumption and cash flow from elapsed-day run rate and recurring charges, with confidence.", inputSchema: { transactions: z.array(transactionInput).optional(), period: z.string().optional() }, annotations: { readOnlyHint: true } }, async ({ transactions, period }) => { const forecast = predictMonthEndSpending(transactions || (await loadLedger()).transactions, period); return result(`Projected consumption for ${forecast.period} is ${currency(forecast.projectedConsumption)} (${forecast.confidence} confidence).`, forecast); });
server.registerTool("financial_timeline", { title: "Financial timeline", description: "Create a concise narrative of the most material financial changes across up to six months.", inputSchema: { transactions: z.array(transactionInput).optional(), budgets: z.array(budgetInput).optional(), months: z.number().int().min(1).max(12).optional().default(6) }, annotations: { readOnlyHint: true } }, async ({ transactions, budgets, months }) => { const timeline = buildFinancialTimeline(transactions || (await loadLedger()).transactions, budgets || [], months); return result(`Built a ${months}-month timeline with ${timeline.length} material events.`, { timeline }); });
server.registerTool("finance_graph", { title: "Finance knowledge graph", description: "Return derived transaction, merchant, category, period, subscription, and budget relationships for connected questions.", inputSchema: { transactions: z.array(transactionInput).optional(), budgets: z.array(budgetInput).optional() }, annotations: { readOnlyHint: true } }, async ({ transactions, budgets }) => { const graph = buildFinanceGraph(transactions || (await loadLedger()).transactions, budgets || []); return result(`Built a finance graph with ${graph.nodes.length} nodes and ${graph.edges.length} relationships.`, { graph }); });
server.registerTool("parse_statement", { title: "Parse statement", description: "Extract raw canonical transactions without categorizing, saving, or syncing.", inputSchema: { filePath: z.string() }, annotations: { readOnlyHint: true } }, async ({ filePath }) => { const transactions = await parseFile(filePath); return result(`Parsed ${transactions.length} raw transactions.`, { transactions, count: transactions.length, source: path.basename(filePath) }); });
server.registerTool("categorize_transactions", { title: "Categorize transactions", description: "Normalize merchants and categorize supplied transactions with confidence and explanations; has no side effects.", inputSchema: { transactions: z.array(transactionInput) }, annotations: { readOnlyHint: true } }, async ({ transactions }) => { const categorized = await categorize(transactions); return result(`Categorized ${categorized.length} transactions.`, { transactions: categorized, count: categorized.length }); });
server.registerTool("normalize_merchants", { title: "Normalize merchants", description: "Canonicalize merchant variants without changing categories or saving.", inputSchema: { transactions: z.array(transactionInput) }, annotations: { readOnlyHint: true } }, async ({ transactions }) => { const normalized = transactions.map((t) => ({ ...t, merchant: normalizeMerchant(t.merchant || t.description) })); return result(`Normalized ${normalized.length} merchants.`, { transactions: normalized }); });
server.registerTool("save_transactions", { title: "Save transactions", description: "Persist reviewed transactions to the local Finora ledger only after user approval.", inputSchema: { transactions: z.array(transactionInput), replace: z.boolean().optional().default(false) } }, async ({ transactions, replace }) => { const ledger = replace ? { currency: "INR", transactions: [] } : await loadLedger(); ledger.transactions.push(...transactions); await saveLedger(ledger); return result(`Saved ${transactions.length} transactions.`, { saved: transactions.length, ledgerPath: LEDGER_PATH, total: ledger.transactions.length }); });
server.registerTool("summarize_transactions", { title: "Summarize transactions", description: "Calculate totals for supplied transactions and optional month without saving.", inputSchema: { transactions: z.array(transactionInput), period: z.string().optional() }, annotations: { readOnlyHint: true } }, async ({ transactions, period }) => { const selected = period ? inPeriod(transactions, period) : transactions; return result(JSON.stringify(summarize(selected), null, 2), { period: period || null, ...summarize(selected) }); });
server.registerTool("monthly_summary", { title: "Monthly summary", description: "Summarize each imported month, excluding Transfers and Investments from consumption.", inputSchema: { transactions: z.array(transactionInput).optional() }, annotations: { readOnlyHint: true } }, async ({ transactions }) => { const source = transactions || (await loadLedger()).transactions; const months = monthlySummaries(source); return result(JSON.stringify(months, null, 2), { months }); });
server.registerTool("merchant_analysis", { title: "Merchant analysis", description: "Aggregate spending and frequency by normalized merchant.", inputSchema: { transactions: z.array(transactionInput).optional(), query: z.string().optional() }, annotations: { readOnlyHint: true } }, async ({ transactions, query }) => { const source = transactions || (await loadLedger()).transactions, merchants = Object.values(source.filter((t) => t.type === "debit" && (!query || normalizeMerchant(t.merchant).toLowerCase().includes(query.toLowerCase()))).reduce((acc, t) => { const merchant = normalizeMerchant(t.merchant); acc[merchant] ||= { merchant, total: 0, count: 0, average: 0, transactions: [] }; acc[merchant].total += t.amount; acc[merchant].count++; acc[merchant].transactions.push(t.id); acc[merchant].average = acc[merchant].total / acc[merchant].count; return acc; }, {})).sort((a, b) => b.total - a.total); return result(JSON.stringify(merchants, null, 2), { merchants }); });
server.registerTool("detect_subscriptions", { title: "Detect subscriptions", description: "Find recurring merchants from cadence and amount consistency and estimate monthly/annual cost and renewal.", inputSchema: { transactions: z.array(transactionInput).optional() }, annotations: { readOnlyHint: true } }, async ({ transactions }) => { const found = subscriptions(transactions || (await loadLedger()).transactions); return result(JSON.stringify(found, null, 2), { subscriptions: found, monthlyCost: found.reduce((a, s) => a + s.monthlyCost, 0) }); });
server.registerTool("find_duplicate_transactions", { title: "Find duplicate transactions", description: "Find same-merchant, same-amount debit pairs within two minutes.", inputSchema: { transactions: z.array(transactionInput).optional() }, annotations: { readOnlyHint: true } }, async ({ transactions }) => { const found = duplicates(transactions || (await loadLedger()).transactions); return result(JSON.stringify(found, null, 2), { duplicates: found }); });
server.registerTool("detect_spending_anomalies", { title: "Detect spending anomalies", description: "Find new high-value merchants and material category jumps against prior imported months.", inputSchema: { transactions: z.array(transactionInput).optional() }, annotations: { readOnlyHint: true } }, async ({ transactions }) => { const found = anomalies(transactions || (await loadLedger()).transactions); return result(JSON.stringify(found, null, 2), { anomalies: found }); });
server.registerTool("spending_trends", { title: "Spending trends", description: "Return monthly consumption, income, savings, transfers, and category totals.", inputSchema: { transactions: z.array(transactionInput).optional() }, annotations: { readOnlyHint: true } }, async ({ transactions }) => { const months = monthlySummaries(transactions || (await loadLedger()).transactions); return result(JSON.stringify(months, null, 2), { months }); });
server.registerTool("compare_months", { title: "Compare months", description: "Compare two statement months and report spending change.", inputSchema: { transactions: z.array(transactionInput).optional(), current: z.string().optional(), previous: z.string().optional() }, annotations: { readOnlyHint: true } }, async ({ transactions, current, previous }) => { const comparison = compareMonths(transactions || (await loadLedger()).transactions, current, previous); return result(JSON.stringify(comparison, null, 2), comparison); });
server.registerTool("budget_status", { title: "Budget status", description: "Calculate category budget usage and warnings for an optional month.", inputSchema: { budgets: z.array(budgetInput), transactions: z.array(transactionInput).optional(), period: z.string().optional() }, annotations: { readOnlyHint: true } }, async ({ budgets, transactions, period }) => { const status = budgetStatus(transactions || (await loadLedger()).transactions, budgets, period); return result(JSON.stringify(status, null, 2), { budgets: status }); });
server.registerTool("financial_health_score", { title: "Financial health score", description: "Return a transparent 0-100 score from savings, budget adherence, recurring cost, and anomaly consistency.", inputSchema: { budgets: z.array(budgetInput).optional(), transactions: z.array(transactionInput).optional() }, annotations: { readOnlyHint: true } }, async ({ budgets, transactions }) => { const score = healthScore(transactions || (await loadLedger()).transactions, budgets || []); return result(JSON.stringify(score, null, 2), score); });
server.registerTool("search_transactions", { title: "Search transactions", description: "Search reviewed ledger transactions by merchant, narration, or category.", inputSchema: { query: z.string().optional(), category: z.string().optional(), limit: z.number().int().min(1).max(500).optional().default(50) }, annotations: { readOnlyHint: true } }, async ({ query, category, limit }) => { const ledger = await loadLedger(), needle = query?.toLowerCase(), transactions = ledger.transactions.filter((t) => (!category || t.category === category) && (!needle || `${t.merchant} ${t.description} ${t.category}`.toLowerCase().includes(needle))).slice(0, limit); return result(JSON.stringify(transactions, null, 2), { transactions, count: transactions.length }); });
server.registerTool("answer_finance_question", { title: "Answer finance question", description: "Answer a natural-language question from the local ledger with evidence.", inputSchema: { question: z.string() }, annotations: { readOnlyHint: true } }, async ({ question }) => { const ledger = await loadLedger(), answer = await answerLedgerQuestion(question, ledger.transactions); return result(answer, { answer }); });
server.registerTool("sync_to_sheet", { title: "Sync supplied transactions to Google Sheets", description: "Write only the supplied reviewed transactions and build report tabs/charts through a Finora Apps Script webhook.", inputSchema: { transactions: z.array(transactionInput), webhookUrl: z.string().url(), secret: z.string().optional() } }, async ({ transactions, webhookUrl, secret }) => { const response = await fetch(webhookUrl, { method: "POST", headers: { "Content-Type": "text/plain;charset=utf-8" }, body: JSON.stringify({ secret, statement: { transactions, period: `${latestPeriod(transactions)}`, currency: "INR", insights: [] } }), redirect: "follow" }); const payload = JSON.parse(await response.text()); if (!response.ok || payload.ok === false) throw new Error(payload.error || "Sheets sync failed."); return result(`Synced ${transactions.length} reviewed transactions.`, payload); });
server.registerTool("export_sheet", { title: "Export ledger to Google Sheets", description: "Export the reviewed local ledger to Google Sheets through a Finora Apps Script webhook.", inputSchema: { webhookUrl: z.string().url(), secret: z.string().optional() } }, async ({ webhookUrl, secret }) => { const ledger = await loadLedger(); const response = await fetch(webhookUrl, { method: "POST", headers: { "Content-Type": "text/plain;charset=utf-8" }, body: JSON.stringify({ secret, statement: { ...ledger, period: latestPeriod(ledger.transactions) } }), redirect: "follow" }); const payload = JSON.parse(await response.text()); if (!response.ok || payload.ok === false) throw new Error(payload.error || "Sheets export failed."); return result(`Exported ${ledger.transactions.length} transactions.`, payload); });

// Backward-compatible convenience tools. Agents should prefer the composable tools above.
server.registerTool("import_statement", { title: "Import statement (convenience)", description: "Parse, categorize, and save a statement in one call. Prefer composable tools when review or partial execution matters.", inputSchema: { filePath: z.string(), replace: z.boolean().optional().default(false) } }, async ({ filePath, replace }) => { const parsed = await parseFile(filePath), categorized = await categorize(parsed), ledger = replace ? { currency: "INR", transactions: [] } : await loadLedger(); ledger.transactions.push(...categorized); await saveLedger(ledger); return result(`Imported ${categorized.length} transactions.`, { imported: categorized.length, transactions: categorized, summary: summarize(ledger.transactions), ledgerPath: LEDGER_PATH }); });
server.registerTool("get_spending_summary", { title: "Get spending summary", description: "Summarize the latest month in the local ledger.", inputSchema: {}, annotations: { readOnlyHint: true } }, async () => { const ledger = await loadLedger(), period = latestPeriod(ledger.transactions), totals = summarize(inPeriod(ledger.transactions, period)); return result(JSON.stringify(totals, null, 2), { period, ...totals }); });
server.registerTool("list_transactions", { title: "List transactions", description: "Backward-compatible ledger search.", inputSchema: { query: z.string().optional(), category: z.string().optional(), limit: z.number().int().min(1).max(500).optional().default(50) }, annotations: { readOnlyHint: true } }, async ({ query, category, limit }) => { const ledger = await loadLedger(), needle = query?.toLowerCase(), transactions = ledger.transactions.filter((t) => (!category || t.category === category) && (!needle || `${t.merchant} ${t.description}`.toLowerCase().includes(needle))).slice(0, limit); return result(JSON.stringify(transactions, null, 2), { transactions, count: transactions.length }); });
server.registerTool("correct_category", { title: "Correct category", description: "Apply a user-confirmed correction to a saved transaction.", inputSchema: { transactionId: z.string(), category: z.enum(categories) } }, async ({ transactionId, category }) => { const ledger = await loadLedger(), transaction = ledger.transactions.find((t) => t.id === transactionId); if (!transaction) throw new Error("Transaction not found."); transaction.category = category; transaction.confidence = 1; transaction.explanation = "Category confirmed by the user."; await saveLedger(ledger); return result(`Updated ${transaction.merchant} to ${category}.`, { transaction }); });
server.registerTool("sync_to_google_sheets", { title: "Sync ledger to Google Sheets", description: "Backward-compatible local-ledger Sheets sync.", inputSchema: { webhookUrl: z.string().url(), secret: z.string().optional() } }, async ({ webhookUrl, secret }) => { const ledger = await loadLedger(); const response = await fetch(webhookUrl, { method: "POST", headers: { "Content-Type": "text/plain;charset=utf-8" }, body: JSON.stringify({ secret, statement: ledger }), redirect: "follow" }); const payload = JSON.parse(await response.text()); if (!response.ok || payload.ok === false) throw new Error(payload.error || "Sheets sync failed."); return result(`Synced ${ledger.transactions.length} transactions.`, payload); });

await server.connect(new StdioServerTransport());
